name: common_dimensions
description: A collection of general dimensions
version: 0.0.1
homepage: https://github.com/helloyeseul/flutter_general_packages
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
