include: all_lint_rules.yaml

analyzer:
  #  strong-mode:
  #      implicit-casts: false
  #    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error

    todo: warning
    prefer_single_quotes: warning

    always_put_control_body_on_new_line: ignore
    sort_pub_dependencies: ignore
    avoid_setters_without_getters: ignore
    slash_for_doc_comments: ignore
    public_member_api_docs: ignore
    prefer_expression_function_bodies: ignore
    always_put_required_named_parameters_first: ignore
    sort_constructors_first: ignore
    diagnostic_describe_all_properties: ignore
    prefer_final_parameters: ignore
    avoid_bool_literals_in_conditional_expressions: ignore

#    included_file_warning: ignore
#    sdk_version_async_exported_from_core: ignore
#    argument_type_not_assignable: ignore
#    implicit_dynamic_type: ignore
#    invalid_assignment: ignore
#    implicit_dynamic_map_literal: ignore

linter:
  rules:
