name: common_utils
description: A collection of general utils
version: 0.0.1
homepage: https://github.com/helloyeseul/flutter_general_packages
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.5 # uuid

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
