name: common_widgets
description: A collection of general widgets
version: 0.0.1
homepage: https://github.com/helloyeseul/flutter_general_packages
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
